service:
  name: ServerlessAPP

plugins:
  - serverless-bundle
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  environment:
    EVENTS_TABLE_NAME: ${self:custom.EventsTable.name}
  iamRoleStatements:
    - ${file(iam/EventsTableIAM.yml):EventsTableIAM}

resources:
  Resources:
    EventsTable: ${file(resources/EventsTable.yml):EventsTable}
  
functions:
  createEvent:
    handler: src/handlers/createEvent.handler
    events:
      - http:
          method: POST
          path: /events
  getEvents:
    handler: src/handlers/getEvents.handler
    events:
      - http:
          method: GET
          path: /events
  getEventById:
    handler: src/handlers/getEventById.handler
    events:
      - http:
          method: GET
          path: /events/{id}

custom:
  EventsTable:
    name: !Ref EventsTable
    arn: !GetAtt EventsTable.Arn
