EventsTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: EventsTable-${self:provider.stage}
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
      - AttributeName: title
        AttributeType: S
      - AttributeName: status
        AttributeType: S
      - AttributeName: nextTime
        AttributeType: S
      - AttributeName: endingAt
        AttributeType: S
    KeySchema:
      - AttributeName: id
        KeyType: HASH
    GlobalSecondaryIndexes:
      - IndexName: statusIndex
        KeySchema:
          - AttributeName: status
            KeyType: HASH
        Projection:
          ProjectionType: ALL