EventsBucket:
  Type: AWS::S3::Bucket
  Properties:
    BucketName: ${self:custom.EventsBucket.name}

EventsBucketPolicy:
  Type: AWS::S3::BucketPolicy
  Properties:
    Bucket: !Ref EventsBucket
    PolicyDocument:
      Statement:
        - Sid: PublicRead
          Effect: Allow
          Principal: '*'
          Action:
            - s3:GetObject
          Resource: arn:aws:s3:::${self:custom.EventsBucket.name}/*