service: ServerlessAPP

plugins:
  - serverless-bundle
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  environment:
    EVENTS_TABLE_NAME: ${self:custom.EventsTable.name}
  iamRoleStatements:
    - ${file(iam/EventsTableIAM.yml):EventsTableIAM}
  apiGateway:
    shouldStartNameWithService: true
  lambdaHashingVersion: "20201221"

resources:
  Resources:
    EventsTable: ${file(resources/EventsTable.yml):EventsTable}
  
functions:
  createEvent:
    handler: src/handlers/createEvent.handler
    events:
      - http:
          method: POST
          path: /events
          authorizer: ${self:custom.authorizer}
  getEvents:
    handler: src/handlers/getEvents.handler
    events:
      - http:
          method: GET
          path: /events
          authorizer: ${self:custom.authorizer}
  deleteEvent:
    handler: src/handlers/deleteEvent.handler
    events:
      - http:
          method: DELETE
          path: /events/{id}
          authorizer: ${self:custom.authorizer}
  getEventById:
    handler: src/handlers/getEventById.handler
    events:
      - http:
          method: GET
          path: /events/{id}
          authorizer: ${self:custom.authorizer}
  addSuscriber:
    handler: src/handlers/addSuscriber.handler
    events:
      - http:
          method: POST
          path: /events/{id}/suscribers
          authorizer: ${self:custom.authorizer}
  removeSuscriber:
    handler: src/handlers/removeSuscriber.handler
    events:
      - http:
          method: DELETE
          path: /events/{id}/suscribers
          authorizer: ${self:custom.authorizer}
  scheduleNextEvents:
    handler: src/handlers/scheduleNextEvents.handler


custom:
  EventsTable:
    name: !Ref EventsTable
    arn: !GetAtt EventsTable.Arn
  authorizer: arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:auth-service-dev-auth
  bundle:
    linting: false
